# Generated by Django 2.2.14 on 2020-07-08 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_prueba', models.TextField()),
                ('laboratorio', models.TextField()),
                ('estado', models.TextField()),
                ('encargado', models.TextField()),
                ('comentario', models.CharField(max_length=200)),
                ('fecha_prueba', models.DateTimeField(blank=True, null=True)),
                ('ID_prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
