# Generated by Django 2.2.14 on 2020-07-08 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coca', '0002_reporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='encargado',
        ),
    ]
